/// Flutter icons Appicons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Appicons
///      fonts:
///       - asset: fonts/Appicons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class Appicons {
  Appicons._();

  static const _kFontFam = 'Appicons';
  static const _kFontPkg = null;

  static const IconData star_circled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData go = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartfull = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
